name: Hello World Multiple Triggers Workflow

on:
    push:
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: '11 4 * * *'  # 04:11 UTC = 9:11 PM PDT

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello World Multiple Triggers"
